kind: Service
apiVersion: v1
metadata:
  name: "postgresql-service"
  namespace: turbo-infra
spec:
  selector:
    app: postgresql
  ports:
    - protocol: "TCP"
      port: 5432
      targetPort: 5432
      nodePort: 32300
  type: NodePort
